version: '3'
services:
    b2w_app:
        container_name: b2w_app
        build: .
        ports:
            - "8080:8080"
        volumes:
            - .:/app
        depends_on:
          - b2w_db
        networks:
          - b2w_network

    b2w_db:
        image: mysql
        container_name: b2w_db
        volumes:
        - /app/database
        ports:
          - "5000:5000"
        networks:
            - b2w_network
networks:
  b2w_network:
      driver: bridge